- name: Deployment Web Servers
  hosts: webservers
  tasks:

    - name: install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
      become: yes

    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
      become: yes

    - name: Run Image
      shell: |
        docker run -it -d -e "DATABASE_URL=postgres://postgres:RjPv8lAoinZs0YBB4Yuz@database.c3jg9feca2co.eu-central-1.rds.amazonaws.com:5432/postgres" -p 80:8000 zabih.azurecr.io/rest-api
      become: yes
    
    - name: migrate
      shell: |
        for container in $(sudo docker ps | grep basic | awk '{print $1}'); do sudo docker exec $container python3 manage.py migrate; done
      become: yes